const http = require('http');
const fs = require('fs');
const path = require('path');
const { URL } = require('url');

const PORT = Number(process.env.PORT) || 3000;
const HOST = process.env.HOST || '0.0.0.0';
const publicDir = path.join(__dirname, 'public');

const mimeTypes = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.ico':'image/x-icon','.woff':'font/woff','.woff2':'font/woff2'};
const eras=[{id:1,slug:'ancient',title:'පුරාණ යුගය',englishTitle:'Ancient Era',includes:['oral and visual signals','inscriptions','ola manuscripts']},{id:2,slug:'middle',title:'මධ්‍ය යුගය',englishTitle:'Middle Era',includes:['printing','telegraph','telephone','radio']},{id:3,slug:'modern',title:'නූතන යුගය',englishTitle:'Modern Era',includes:['mobile','internet','cloud','AI']}];
const experience={title:'Signal Lanka — Communication Museum',version:'11.0.0',mode:'interactive-museum-spa',languages:['si','en'],features:['three-era-story','interactive-simulations','optimized-editorial-museum-ui','archive-photography','interactive-signal-labs','museum-map','responsive-layout','web-audio-feedback','communication-time-machine','60-second-challenge','shareable-exhibition-result'],eras:eras.length};
const timeline=[{era:1,label:'Ancient Era',transformation:'Voice, gesture and visible signals evolve into durable inscriptions and manuscript records.'},{era:2,label:'Middle Era',transformation:'Printing multiplies messages while telegraph, telephone and radio accelerate them across distance.'},{era:3,label:'Modern Era',transformation:'Communication converges into mobile, internet and AI-powered software systems.'}];
function sendJson(res,statusCode,value){const body=JSON.stringify(value);res.writeHead(statusCode,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(body)}
function sendFile(res,filePath){fs.stat(filePath,(statErr,stats)=>{if(statErr||!stats.isFile()){const fallback=path.join(publicDir,'index.html');return fs.readFile(fallback,(fallbackErr,data)=>{if(fallbackErr){res.writeHead(500,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Internal Server Error')}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff'});res.end(data)})}const ext=path.extname(filePath).toLowerCase();res.writeHead(200,{'Content-Type':mimeTypes[ext]||'application/octet-stream','Content-Length':stats.size,'Cache-Control':['.html','.css','.js'].includes(ext)?'no-store, max-age=0':'public, max-age=3600','X-Content-Type-Options':'nosniff'});fs.createReadStream(filePath).pipe(res)})}
const server=http.createServer((req,res)=>{const url=new URL(req.url,`http://${req.headers.host||`localhost:${PORT}`}`);if(req.method!=='GET'&&req.method!=='HEAD')return sendJson(res,405,{error:'Method not allowed'});if(url.pathname==='/api/health')return sendJson(res,200,{ok:true,app:'sri-lanka-communication-journey',runtime:`Node ${process.version}`,timestamp:new Date().toISOString()});if(url.pathname==='/api/eras')return sendJson(res,200,eras);if(url.pathname==='/api/experience')return sendJson(res,200,experience);if(url.pathname==='/api/timeline')return sendJson(res,200,timeline);const pathname=decodeURIComponent(url.pathname),requestedPath=pathname==='/'?'/index.html':pathname,normalizedPath=path.normalize(requestedPath).replace(/^(\.\.[/\\])+/,'');const filePath=path.join(publicDir,normalizedPath);if(!filePath.startsWith(publicDir))return sendJson(res,403,{error:'Forbidden'});sendFile(res,filePath)});
server.listen(PORT,HOST,()=>console.log(`Sri Lanka Communication Journey running at http://localhost:${PORT}`));
